name: 'CloudIL Cloud CR "Login" Action for GitHub Actions'
description: 'Logs in the local Docker client to CloudIL CR'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  cloudil-sa-json-credentials:
    description: 'Json containing authorized key for Service Account. More info https://cloudil.co.il/docs/container-registry/operations/authentication'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'
